image: registry.ci.infra.lan:5000/project-1:server-build_QA

stages:
  - QA

before_script:
  - export GROUP_NUMBER=${CI_PROJECT_NAMESPACE##*-}
  - echo -e "server.port=$((8000 + 10#$GROUP_NUMBER))\nspec.url=https://project-1.ti.howest.be/2024-2025/splendor-api-spec/splendor-api-spec.yaml" > server/src/main/resources/config.properties
  - ln -s /home/gradle/.gradle .gradle

testing:
  stage: QA
  rules:
    - if:
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - gradle clean test --info
    - gradle sonarqube
  artifacts:
    when: always
    reports:
      junit: server/build/test-results/test/**/TEST-*.xml
